[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin=lib/openzeppelin-contracts',
    'forge-std/=lib/forge-std/src/',
]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200