[default]
src = 'contracts'
out = 'out'
libs = ['lib','node_modules']
ffi = true
initial_balance = '0xe22ea493b30310a770000000' # 70000000000000000000000000000
remappings = [
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
names = true
sizes = true


# See more config options https://github.com/foundry-rs/foundry/tree/master/config